### PR TITLE
Fixed System.MissingMethodException

### PR DESCRIPTION
**Pull request by sergey-tihon**
https://github.com/fsprojects/FsUnit/issues/23#issuecomment-127085550

I fixed it like this:
- Add `prerelease` to FsUnit package in `paket.dependencies`
- Call `.paket\paket.exe update`
- Add `FSharp.Core` to both `paket.references` files
- Call `.paket\paket.exe install --hard`
- Add `App.config` file to the test project
- Call `.paket\paket.exe install --redirects`

### CODE REVIEW

**Comment by sideeffffect** [comment]
wow, thanks a lot!
but can we do something about `ProjectScaffold` so that things like this work out of the box?

**Comment by sergey-tihon** [comment]
`ProjectScaffold` does not have dependency on `FsUnit` neither `FsCheck`.
Difficulty comes when integrating the two

**Comment by rneatherway** [comment]
@sergey-tihon this comes up pretty often, and this is a great automated way of fixing it. I think it would be well worth including this in the FsUnit docs.

**Comment by sideeffffect** [comment]
I presume that both `FsUnit` and `FsCheck` are popular libraries, so would it be thinkable to include them into `ProjectScaffold`? So that it all works out-of-the-box and we can also monitor that it stays that way via Travis.

**Comment by sergey-tihon** [comment]
@rneatherway Agreed, we definitely should add docs with guidelines
- `FsUnit` + `FxCheck` + `NUnit`
- `FsUnit` + `FsCheck` + `XUnit`

**Comment by sergey-tihon** [comment]
@sideeffffect Yes, they are popular but `ProjectScaffold` should be as minimal as possible

**Pull request merged**
